version: "3.1"

services:
  db:
    image: mariadb:10.6
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
